# Generated by Django 5.0.14 on 2026-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_location',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='preferred_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
