# Generated by Django 5.0.14 on 2026-03-29 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_deliveryrequest_delivery_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='vehicle_size',
            field=models.CharField(blank=True, default='', help_text='Required truck capacity or vehicle size', max_length=50),
        ),
    ]
