# Generated by Django 5.0.14 on 2026-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_deliveryrequest_vehicle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='pod_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pod_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pod_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pod/'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pod_recipient_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
