# Generated by Django 5.0.14 on 2026-04-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_deliveryrequest_pod_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_vehicle_id',
            field=models.CharField(blank=True, help_text="ID of the vehicle from transporter's fleet", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='assigned_vehicle_info',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of vehicle details at acceptance'),
        ),
    ]
