# Generated by Django 5.0.14 on 2026-04-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_deliveryrequest_assigned_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('refused_delivery', 'Refused Delivery'), ('return_in_progress', 'Return in Progress'), ('returned', 'Returned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
