# Generated by Django 5.0.14 on 2026-05-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_alter_deliveryrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_wilaya',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
