# Generated by Django 5.0.14 on 2026-05-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_migrate_json_vehicles_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='vehicle_size',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='estimated_distance_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='estimated_duration',
            field=models.CharField(blank=True, default='', help_text='e.g. 1h 35m', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='estimated_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='is_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='is_refrigerated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='required_vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('refrigerated_truck', 'Refrigerated Truck'), ('pickup', 'Pickup'), ('utility', 'Utility Vehicle')], default='truck', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('truck', 'Truck'), ('van', 'Van'), ('refrigerated_truck', 'Refrigerated Truck'), ('pickup', 'Pickup'), ('utility', 'Utility Vehicle')], default='truck', max_length=50),
        ),
    ]
