# Generated by Django 5.0.14 on 2026-05-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_remove_deliveryrequest_vehicle_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='car_photo',
            field=models.ImageField(blank=True, help_text='Photo of the vehicle (optional)', null=True, upload_to='vehicles/photos/'),
        ),
    ]
