# Generated by Django 5.0.14 on 2026-05-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_vehicle_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
