# Generated by Django 5.0.14 on 2026-05-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_deliveryrequest_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('standard', 'Standard (Any)'), ('truck', 'Truck'), ('van', 'Van'), ('refrigerated_truck', 'Refrigerated Truck'), ('pickup', 'Pickup'), ('utility', 'Utility Vehicle')], help_text='The vehicle type this rule applies to.', max_length=50, unique=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum cost just to start the mission.', max_digits=12)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=15.0, help_text='Cost added for each kilometer of travel.', max_digits=10)),
                ('weight_multiplier', models.FloatField(default=0.01, help_text='Multiplier applied based on total weight/quantity. (e.g. price += weight * multiplier)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport Pricing Rule',
                'verbose_name_plural': 'Transport Pricing Rules',
            },
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_latitude',
        ),
        migrations.RemoveField(
            model_name='deliveryrequest',
            name='pickup_longitude',
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='delivery_wilaya',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='pickup_commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='required_vehicle_type',
            field=models.CharField(choices=[('standard', 'Standard (Any)'), ('truck', 'Truck'), ('van', 'Van'), ('refrigerated_truck', 'Refrigerated Truck'), ('pickup', 'Pickup'), ('utility', 'Utility Vehicle')], default='truck', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('standard', 'Standard (Any)'), ('truck', 'Truck'), ('van', 'Van'), ('refrigerated_truck', 'Refrigerated Truck'), ('pickup', 'Pickup'), ('utility', 'Utility Vehicle')], default='truck', max_length=50),
        ),
    ]
