# Generated by Django 5.0.14 on 2026-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_transportpricingrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='inactivity_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='relinquish_proof',
            field=models.ImageField(blank=True, null=True, upload_to='relinquish_proofs/'),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='relinquish_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deliveryrequest',
            name='relinquished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('high_priority', 'High Priority'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('refused_delivery', 'Refused Delivery'), ('return_in_progress', 'Return in Progress'), ('returned', 'Returned'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
    ]
