# Generated by Django 5.0.14 on 2026-03-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('delivery_accepted', 'Delivery Accepted'), ('delivery_completed', 'Delivery Completed'), ('delivery_request', 'Delivery Request'), ('user_approved', 'Account Approved'), ('user_pending', 'User Pending Approval'), ('complaint_update', 'Complaint Status Updated'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
