# Generated by Django 5.0.14 on 2026-05-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_rejected', 'Order Rejected'), ('delivery_accepted', 'Delivery Accepted'), ('delivery_completed', 'Delivery Completed'), ('delivery_request', 'Delivery Request'), ('user_approved', 'Account Approved'), ('user_pending', 'User Pending Approval'), ('complaint_update', 'Complaint Status Updated'), ('farm_approved', 'Farm Approved'), ('farm_rejected', 'Farm Rejected'), ('vehicle_approved', 'Vehicle Approved'), ('vehicle_rejected', 'Vehicle Rejected'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
