# Generated by Django 5.0.14 on 2026-03-25 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon_alter_product_unit_catalogproduct_and_more'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricepublication',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pricepublication',
            name='product',
        ),
        migrations.AddField(
            model_name='pricepublication',
            name='catalog_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='catalog.catalogproduct'),
        ),
        migrations.AddField(
            model_name='pricepublication',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='pricepublication',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='pricepublication',
            name='official_price',
            field=models.DecimalField(decimal_places=2, help_text='The reference/official price set by admin', max_digits=12),
        ),
    ]
