# Generated by Django 5.0.14 on 2026-05-04 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_commune_farm_wilaya'),
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='farms.farm')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
