# Generated by Django 5.0.14 on 2026-05-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alerthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='ir_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='sound_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
