# Generated by Django 5.0.14 on 2026-05-16 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_sensorreading_ir_status_sensorreading_sound_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='ph',
        ),
    ]
