# Generated by Django 5.0.14 on 2026-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0002_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PRICE_ANOMALY', 'Price Anomaly'), ('STOCK_IMBALANCE', 'Stock Imbalance'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('USER_REPORT', 'User Report'), ('VERIFICATION_PENDING', 'Verification Pending'), ('SYSTEM_ALERT', 'System Alert')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alertconfig',
            name='alert_type',
            field=models.CharField(choices=[('PRICE_ANOMALY', 'Price Anomaly'), ('STOCK_IMBALANCE', 'Stock Imbalance'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('USER_REPORT', 'User Report'), ('VERIFICATION_PENDING', 'Verification Pending'), ('SYSTEM_ALERT', 'System Alert')], max_length=50, unique=True),
        ),
    ]
