# Generated by Django 5.0.14 on 2026-05-02 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0003_alter_alert_alert_type_alter_alertconfig_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmessage',
            name='is_reply_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='admin_ops.adminmessage'),
        ),
    ]
