# Generated by Django 5.0.14 on 2026-03-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_buyer_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farmer_order_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
