# Generated by Django 5.0.14 on 2026-03-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_add_farmer_order_number_and_farm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
