# Generated by Django 5.0.14 on 2026-03-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional representative image for this farm.', null=True, upload_to='farms/'),
        ),
    ]
