# Generated by Django 5.0.14 on 2026-04-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_add_farmer_order_number_and_farm_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='commune',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='farm',
            name='wilaya',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
