# Generated by Django 5.0.14 on 2026-05-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_commune_farm_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
