# Generated by Django 5.0.14 on 2026-05-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_set_existing_farms_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='registry_document',
            field=models.FileField(blank=True, help_text='Registry document or certificate for this farm — JPG/PNG/PDF', null=True, upload_to='farms/documents/'),
        ),
    ]
