# Generated by Django 5.0.14 on 2026-05-14 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0007_farm_registry_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='harvestrecord',
            options={'ordering': ['-record_date']},
        ),
        migrations.RenameField(
            model_name='harvestrecord',
            old_name='harvest_date',
            new_name='record_date',
        ),
        migrations.RemoveField(
            model_name='harvestrecord',
            name='yield_quantity',
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='quantity_produced',
            field=models.FloatField(default=0.0, help_text='Quantity in KG or TON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('TON', 'TON'), ('LITER', 'LITER'), ('PIECE', 'PIECE')], default='KG', max_length=20),
        ),
        migrations.AddField(
            model_name='harvestrecord',
            name='year',
            field=models.IntegerField(default=2026),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='crop_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_records', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='harvestrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
