# Generated by Django 5.0.14 on 2026-05-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('CEREALS', 'Cereals'), ('LEGUMES', 'Legumes'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('OTHER', 'Other')], default='VEGETABLES', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=2, help_text='Previous price for change calculation', max_digits=12, null=True)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('trend', models.CharField(choices=[('INCREASING', 'Increasing'), ('DECREASING', 'Decreasing'), ('STABLE', 'Stable')], default='STABLE', max_length=20)),
                ('market_note', models.TextField(blank=True, default='')),
                ('is_highlighted', models.BooleanField(default=False, help_text='If True, this price will appear as a highlighted alert')),
                ('highlight_message', models.CharField(blank=True, default='', help_text='Custom alert message when highlighted', max_length=500)),
                ('ai_prediction', models.JSONField(blank=True, help_text='Reserved for AI market prediction data', null=True)),
                ('weather_impact_score', models.FloatField(blank=True, help_text='Reserved for weather impact analysis', null=True)),
                ('supply_index', models.FloatField(blank=True, help_text='Reserved for supply/demand analytics', null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_prices_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Price',
                'verbose_name_plural': 'Market Prices',
                'ordering': ['-is_highlighted', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('market_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='market_intelligence.marketprice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Market Price History',
                'verbose_name_plural': 'Market Price Histories',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
