# Generated by Django 5.0.14 on 2026-03-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quality',
            field=models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('ECONOMY', 'Economy'), ('ORGANIC', 'Organic')], default='STANDARD', max_length=20),
        ),
    ]
