# Generated by Django 5.0.14 on 2026-05-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_discount_rules',
            field=models.JSONField(blank=True, default=list, help_text="[{'min_qty': 50, 'discount_pct': 5}, ...]"),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order_quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=12),
        ),
    ]
