# Generated by Django 5.0.14 on 2026-05-01 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_document_status_user_is_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size_hectares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('farm_capacity_tons', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmerprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
