# Generated by Django 5.0.14 on 2026-05-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_email_verified_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
