# Generated by Django 5.0.14 on 2026-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('farmer_id', 'Farmer ID'), ('farm_photo', 'Farm Photo'), ('trade_register', 'Trade Register'), ('driving_license', 'Driving License'), ('vehicle_registration', 'Vehicle Registration'), ('car_photo', 'Car Photo')], max_length=30),
        ),
    ]
