# Generated by Django 5.0.14 on 2026-05-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_suspended_until_user_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cancellation_count',
            field=models.IntegerField(default=0),
        ),
    ]
