# Generated by Django 5.0.14 on 2026-05-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_cancellation_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='trust_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trust_score',
        ),
    ]
