export const WILAYA_DATA = [
  { id: "1", name: "Adrar", lat: 27.87, lng: -0.29, communes: ["Adrar", "Tamest", "Charouine", "Reggane", "In Zghmir", "Tit", "Tsabit", "Timokten", "Tinerkouk", "Bouda", "Aoulef", "Fenoughil", "Lardjam"] },
  { id: "2", name: "Chlef", lat: 36.16, lng: 1.33, communes: ["Chlef", "Tenes", "Ouled Fares", "Boukadir", "Oued Fodda", "El Karimia", "Sidi Akkacha", "El Marsa", "Sendjas", "Sidi Abderrahmane"] },
  { id: "3", name: "Laghouat", lat: 33.8, lng: 2.88, communes: ["Laghouat", "Ksar El Hirane", "Bennasser Benchohra", "Sidi Makhlouf", "Hassi Delaa", "Hassi R'Mel", "Ain Madhi", "Tadjemout", "El Kheneg"] },
  { id: "4", name: "Oum El Bouaghi", lat: 35.87, lng: 7.11, communes: ["Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Ain Fakroun", "Ain Kercha", "Hanchir Toumghani", "F'kirina", "Souk Naamane"] },
  { id: "5", name: "Batna", lat: 35.56, lng: 6.17, communes: ["Batna", "Arris", "Barika", "Batna", "Ain Djasser", "Ain Yagout", "N'Gaous", "Merouana", "Tazoult", "Thiet", "Oued Taga"] },
  { id: "6", name: "Béjaïa", lat: 36.76, lng: 5.08, communes: ["Béjaïa", "Amizour", "Seddouk", "Akbou", "El Kseur", "Timezrit", "Souk El Tenine", "Melbou", "Tichy", "Aokas", "Taskriout"] },
  { id: "7", name: "Biskra", lat: 34.85, lng: 5.73, communes: ["Biskra", "Oumache", "Branis", "Cheddi", "El Ghrous", "Tolga", "Sidi Okba", "M'Chouneche", "Zeribet El Oued", "Lichana"] },
  { id: "8", name: "Béchar", lat: 31.62, lng: -2.22, communes: ["Béchar", "Kenadsa", "Lahmar", "Taghit", "Igli", "Tabelbala", "Abadla", "Erghir", "Mouhli"] },
  { id: "9", name: "Blida", lat: 36.47, lng: 2.83, communes: ["Blida", "Boufarik", "Oued Alleug", "Larbaa", "Meftah", "Chebli", "Bouinan", "Bougara", "Soumaa", "Mouzaia", "El Affroun"] },
  { id: "10", name: "Bouira", lat: 36.38, lng: 3.9, communes: ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Ain Bessem", "Bechloul", "M'Chedallah", "Kadiria", "El Hachimia", "Dirah"] },
  { id: "11", name: "Tamanrasset", lat: 22.79, lng: 5.53, communes: ["Tamanrasset", "In Amguel", "Idles", "Tazrouk"] },
  { id: "12", name: "Tébessa", lat: 35.4, lng: 8.12, communes: ["Tébessa", "Bir El Ater", "Cheria", "Ouenza", "El Kouif", "Morsott", "Negrine", "Hammamet", "El Ogla"] },
  { id: "13", name: "Tlemcen", lat: 34.88, lng: -1.31, communes: ["Tlemcen", "Mansourah", "Maghnia", "Ghazaouet", "Remchi", "Hennaya", "Nedroma", "Sebdou", "Ouled Mimoun", "Beni Saf"] },
  { id: "14", name: "Tiaret", lat: 35.37, lng: 1.32, communes: ["Tiaret", "Sougueur", "Frenda", "Ksar Chellala", "Mahdia", "Rahouia", "Dahmouni", "Hamadia", "Oued Lilli"] },
  { id: "15", name: "Tizi Ouzou", lat: 36.71, lng: 4.05, communes: ["Tizi Ouzou", "Ain El Hammam", "Azazga", "Azeffoun", "Beni Douala", "Beni Yenni", "Boghni", "Draa Ben Khedda", "Draa El Mizan", "Larbaa Nath Irathen", "Ouadhias", "Tigzirt"] },
  { id: "16", name: "Alger", lat: 36.75, lng: 3.06, communes: ["Alger Centre", "Sidi M'Hamed", "El Madania", "Belouizdad", "Bab El Oued", "Bologhine", "Casbah", "Oued Koriche", "Birmandreis", "El Biar", "Hydra", "Ben Aknoun", "Bouzareah", "Birkhadem", "El Harrach", "Baraki", "Oued Smar", "Bordj El Kiffan", "Bab Ezzouar", "Dar El Beida", "Reghaia", "Rouiba", "Ain Taya"] },
  { id: "17", name: "Djelfa", lat: 34.67, lng: 3.25, communes: ["Djelfa", "Messaad", "Ain El Ibel", "Hassi Bahbah", "Dar Chioukh", "Charef", "El Idrissia", "Birine", "Sidi Ladjel"] },
  { id: "18", name: "Jijel", lat: 36.82, lng: 5.77, communes: ["Jijel", "Taher", "El Milia", "Chekfa", "El Ancer", "Sidi Abdelaziz", "Kaous", "Settara", "El Aouana", "Ziama Mansouriah"] },
  { id: "19", name: "Sétif", lat: 36.19, lng: 5.41, communes: ["Sétif", "El Eulma", "Bougaa", "Ain Arnat", "Ain Azel", "Ain Oulmene", "Guenzet", "Beni Aziz", "Beni Ourtilane", "Hammam Guergour", "Salah Bey"] },
  { id: "20", name: "Saïda", lat: 34.83, lng: 0.15, communes: ["Saïda", "Ain El Hadjar", "Youb", "Hassi El Ghoula", "Sidi Amar"] },
  { id: "21", name: "Skikda", lat: 36.87, lng: 6.91, communes: ["Skikda", "Azzaba", "El Harrouch", "Collo", "Tamalous", "Azzaba", "Ouled Attia", "Zitouna", "Sidi Mezghiche"] },
  { id: "22", name: "Sidi Bel Abbès", lat: 35.19, lng: -0.63, communes: ["Sidi Bel Abbès", "Tessala", "Sidi Lahcene", "Sidi Ali Benyoub", "Mostefa Ben Brahim", "Tenira", "Telagh", "Moulay Slissen", "Merine"] },
  { id: "23", name: "Annaba", lat: 36.9, lng: 7.77, communes: ["Annaba", "El Bouni", "Sidi Amar", "Berrahal", "Chetaibi", "El Hadjar", "Seraidi"] },
  { id: "24", name: "Guelma", lat: 36.46, lng: 7.43, communes: ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis", "Ain Makhlouf", "Guelaat Bou Sbaa", "Hammama Meskhoutine"] },
  { id: "25", name: "Constantine", lat: 36.37, lng: 6.61, communes: ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Zighoud Youcef", "Ain Smara", "Ouled Rahmoune"] },
  { id: "26", name: "Médéa", lat: 36.26, lng: 2.75, communes: ["Médéa", "Ouzera", "Berrouaghia", "Seghouane", "Ksar El Boukhari", "Chahbounia", "Aziz", "Chellalet El Adhaoura", "Beni Slimane", "Tablat", "El Omaria"] },
  { id: "27", name: "Mostaganem", lat: 35.93, lng: 0.09, communes: ["Mostaganem", "Ain Nouissy", "Hassi Mameche", "Mesra", "Bouguirat", "Sidi Lakhdar", "Achaacha", "Sidi Ali", "Kheir Eddine", "Ain Tedeles"] },
  { id: "28", name: "M'Sila", lat: 35.7, lng: 4.54, communes: ["M'Sila", "Hammam Dhalaa", "Ouled Derradj", "Sidi Aissa", "Ain El Hadjel", "Boussaada", "Ouled Sidi Brahim", "Beni Ilmane", "Maadid"] },
  { id: "29", name: "Mascara", lat: 35.4, lng: 0.14, communes: ["Mascara", "Bou Hanifia", "Oued Taria", "Ghriss", "Tighennif", "Sig", "Mohammadia", "Oued El Abtal", "Aouf"] },
  { id: "30", name: "Ouargla", lat: 31.95, lng: 5.33, communes: ["Ouargla", "Hassi Messaoud", "Rouissat", "Ain Beida", "Sidi Khouiled", "N'Goussa"] },
  { id: "31", name: "Oran", lat: 35.7, lng: -0.63, communes: ["Oran", "Arzew", "Gdyel", "Bethioua", "Es Senia", "Sidi Chami", "Bir El Djir", "Hassi Bounif", "Misserghin", "Boutlelis", "Ain El Turk"] },
  { id: "32", name: "El Bayadh", lat: 33.68, lng: 1.0, communes: ["El Bayadh", "Rogassa", "Bougtob", "El Abiodh Sidi Cheikh", "Brezina", "Boualem"] },
  { id: "33", name: "Illizi", lat: 26.51, lng: 8.48, communes: ["Illizi", "Djanet", "Bordj El Haouas", "In Amenas"] },
  { id: "34", name: "Bordj Bou Arreridj", lat: 36.07, lng: 4.76, communes: ["Bordj Bou Arreridj", "Ras El Oued", "Bordj Ghedir", "Bir Kasdali", "Mansoura", "Medjana", "El Achir"] },
  { id: "35", name: "Boumerdès", lat: 36.77, lng: 3.47, communes: ["Boumerdès", "Boudouaou", "Corso", "Thenia", "Isser", "Si Mustapha", "Zemmouri", "Baghlia", "Dellys", "Khemis El Khechna", "Hamadi"] },
  { id: "36", name: "El Tarf", lat: 36.77, lng: 8.31, communes: ["El Tarf", "El Kala", "Ben M'Hidi", "Besbes", "Drean", "Bouhadjar"] },
  { id: "37", name: "Tindouf", lat: 27.67, lng: -8.15, communes: ["Tindouf", "Oum El Assel"] },
  { id: "38", name: "Tissemsilt", lat: 35.6, lng: 1.81, communes: ["Tissemsilt", "Khemisti", "Theiniet El Had", "Lardjam", "Bordj Bou Naama"] },
  { id: "39", name: "El Oued", lat: 33.37, lng: 6.86, communes: ["El Oued", "Robbah", "Bayadha", "Guemar", "Reguiba", "Magrane", "Debila", "Hassi Khalifa", "Taleb Larbi"] },
  { id: "40", name: "Khenchela", lat: 35.43, lng: 7.14, communes: ["Khenchela", "Kais", "El Hamma", "Bouhmama", "Chechar", "Babar"] },
  { id: "41", name: "Souk Ahras", lat: 36.29, lng: 7.95, communes: ["Souk Ahras", "Sedrata", "M'daourouch", "Taoura", "Haddada"] },
  { id: "42", name: "Tipaza", lat: 36.59, lng: 2.45, communes: ["Tipaza", "Cherchell", "Kolea", "Ahmer El Ain", "Bou Ismail", "Fouka", "Gouraya", "Damous", "Sidi Amar"] },
  { id: "43", name: "Mila", lat: 36.45, lng: 6.26, communes: ["Mila", "Chelghoum Laid", "Teleghma", "Grarem Gouga", "Ferdjioua", "Rouached", "Sidi Merouane"] },
  { id: "44", name: "Aïn Defla", lat: 36.26, lng: 1.97, communes: ["Aïn Defla", "Khemis Miliana", "Miliana", "Boumedfaa", "El Attaf", "Djelida", "Djendel", "Bourached"] },
  { id: "45", name: "Naâma", lat: 33.27, lng: -0.31, communes: ["Naâma", "Mecheria", "Ain Sefra", "Asla", "Tiout"] },
  { id: "46", name: "Aïn Témouchent", lat: 35.3, lng: -1.14, communes: ["Aïn Témouchent", "Beni Saf", "Hammam Bou Hadjar", "El Amria", "El Malah"] },
  { id: "47", name: "Ghardaïa", lat: 32.49, lng: 3.67, communes: ["Ghardaïa", "Bounoura", "El Atteuf", "Metlili", "Zelfana", "Guerrara", "Berriane"] },
  { id: "48", name: "Relizane", lat: 35.74, lng: 0.56, communes: ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa", "Zemmora", "Matmar", "Djidiouia"] },
  { id: "49", name: "El M'Ghair", lat: 33.53, lng: 5.93, communes: ["El M'Ghair", "Djamaa"] },
  { id: "50", name: "El Meniaa", lat: 30.58, lng: 2.88, communes: ["El Meniaa", "Hassi Gara"] },
  { id: "51", name: "Ouled Djellal", lat: 34.43, lng: 5.07, communes: ["Ouled Djellal", "Sidi Khaled"] },
  { id: "52", name: "Bordj Baji Mokhtar", lat: 21.33, lng: 0.95, communes: ["Bordj Baji Mokhtar", "Timiaouine"] },
  { id: "53", name: "Béni Abbès", lat: 30.13, lng: -2.17, communes: ["Béni Abbès", "Kerzaz", "Igli", "El Ouata", "Tabelbala"] },
  { id: "54", name: "Timimoun", lat: 29.26, lng: 0.23, communes: ["Timimoun", "Aougrout", "Ksar Kaddour"] },
  { id: "55", name: "Touggourt", lat: 33.1, lng: 6.07, communes: ["Touggourt", "Nezla", "Tebesbest", "Zaouia El Abidia"] },
  { id: "56", name: "Djanet", lat: 24.55, lng: 9.48, communes: ["Djanet", "Bordj El Haouas"] },
  { id: "57", name: "In Salah", lat: 27.19, lng: 2.47, communes: ["In Salah", "Foggaret Ezzaouia"] },
  { id: "58", name: "In Guezzam", lat: 19.57, lng: 5.77, communes: ["In Guezzam", "Tin Zaouatine"] }

];
