# Generated by Django 5.0.14 on 2026-03-30 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0003_deliveryrequest_vehicle_size'),
        ('orders', '0004_add_farmer_order_number_and_farm_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('complaint_type', models.CharField(choices=[('ORDER', 'Order Issue'), ('DELIVERY', 'Delivery Problem'), ('PRODUCT', 'Product Quality'), ('PAYMENT', 'Payment/Transaction'), ('OTHER', 'Other')], default='ORDER', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('attachment', models.ImageField(blank=True, null=True, upload_to='complaints/evidence/')),
                ('admin_notes', models.TextField(blank=True, default='', help_text='Notes from admin on resolution')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_complaints', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='logistics.deliveryrequest')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='orders.order')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
